server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ctrl08/SpringCloud_Learn.git
          search-paths: config
          username: Ctrl08
          password: Lidahao1
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8071/eureka/
#  instance:
#    prefer-ip-address: true